# Generated by Django 5.2.7 on 2025-10-10 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="owner",
            name="aadhar_number",
            field=models.CharField(blank=True, max_length=12, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name="owner",
            name="pan_number",
            field=models.CharField(blank=True, max_length=10, null=True, unique=True),
        ),
    ]
