# Generated by Django 5.2.7 on 2025-10-11 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_alter_owner_aadhar_number_alter_owner_pan_number"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tenant",
            name="address",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AlterField(
            model_name="tenant",
            name="city",
            field=models.CharField(blank=True, default="", max_length=100),
        ),
        migrations.AlterField(
            model_name="tenant",
            name="emergency_contact",
            field=models.CharField(blank=True, default="", max_length=15),
        ),
        migrations.AlterField(
            model_name="tenant",
            name="emergency_contact_name",
            field=models.CharField(blank=True, default="", max_length=100),
        ),
        migrations.AlterField(
            model_name="tenant",
            name="phone",
            field=models.CharField(blank=True, default="", max_length=15),
        ),
        migrations.AlterField(
            model_name="tenant",
            name="pincode",
            field=models.CharField(blank=True, default="", max_length=10),
        ),
        migrations.AlterField(
            model_name="tenant",
            name="state",
            field=models.CharField(blank=True, default="", max_length=100),
        ),
    ]
