# Generated by Django 5.2.7 on 2025-10-11 13:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_tenant_address_alter_tenant_city_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='emergency_contact',
            field=models.CharField(blank=True, default='', max_length=15),
        ),
        migrations.CreateModel(
            name='MaintenanceContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('service_type', models.CharField(choices=[('plumber', 'Plumber'), ('electrician', 'Electrician'), ('carpenter', 'Carpenter'), ('ac_technician', 'AC Technician'), ('housekeeping', 'Housekeeping'), ('security', 'Security'), ('other', 'Other')], max_length=20)),
                ('phone', models.CharField(max_length=15)),
                ('description', models.TextField(blank=True)),
                ('is_emergency', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='maintenance_contacts', to='core.property')),
            ],
        ),
    ]
