# Generated by Django 5.2.7 on 2025-10-11 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_property_emergency_contact_maintenancecontact'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='maintenance_contacts',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.DeleteModel(
            name='MaintenanceContact',
        ),
    ]
