# Generated by Django 5.2.7 on 2025-10-11 15:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_property_maintenance_contacts_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='merchant_order_id',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='paymenttransaction',
            name='merchant_order_id',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='paymenttransaction',
            name='payment_attempt_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='paymenttransaction',
            name='reconciliation_status',
            field=models.CharField(choices=[('not_started', 'Not Started'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('failed', 'Failed')], default='not_started', max_length=20),
        ),
        migrations.CreateModel(
            name='OwnerSubscriptionPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment_type', models.CharField(default='subscription', max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('payment_date', models.DateTimeField(blank=True, null=True)),
                ('due_date', models.DateField()),
                ('subscription_period', models.CharField(choices=[('monthly', 'Monthly'), ('yearly', 'Yearly')], max_length=20)),
                ('subscription_start_date', models.DateTimeField(blank=True, null=True)),
                ('subscription_end_date', models.DateTimeField(blank=True, null=True)),
                ('merchant_order_id', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('phonepe_order_id', models.CharField(blank=True, max_length=100)),
                ('phonepe_transaction_id', models.CharField(blank=True, max_length=100)),
                ('payment_gateway_response', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscription_payments', to='core.owner')),
                ('pricing_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscription_payments', to='core.pricingplan')),
            ],
        ),
    ]
