# Generated by Django 5.2.7 on 2025-10-11 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_property_maintenance_contacts_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="owner",
            name="profile_image",
            field=models.ImageField(blank=True, null=True, upload_to="owner_profiles/"),
        ),
    ]
