# Generated by Django 5.2.7 on 2025-10-12 08:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_payment_merchant_order_id_and_more'),
        ('core', '0007_owner_date_of_birth_owner_emergency_contact_and_more'),
    ]

    operations = [
    ]
