# Generated by Django 5.2.7 on 2025-10-12 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0008_merge_20251012_0838"),
    ]

    operations = [
        migrations.AddField(
            model_name="owner",
            name="account_number",
            field=models.CharField(blank=True, default="", max_length=20),
        ),
        migrations.AddField(
            model_name="owner",
            name="bank_name",
            field=models.CharField(blank=True, default="", max_length=100),
        ),
        migrations.AddField(
            model_name="owner",
            name="ifsc_code",
            field=models.CharField(blank=True, default="", max_length=11),
        ),
        migrations.AddField(
            model_name="owner",
            name="payment_method",
            field=models.CharField(
                blank=True,
                choices=[("bank", "Bank Details"), ("upi", "UPI")],
                max_length=10,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="owner",
            name="upi_id",
            field=models.CharField(blank=True, default="", max_length=100),
        ),
    ]
