# Generated by Django 5.2.7 on 2025-10-12 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0010_userprofile"),
    ]

    operations = [
        migrations.AddField(
            model_name="owner",
            name="auth_method",
            field=models.CharField(
                choices=[
                    ("email", "Email/Password"),
                    ("google", "Google"),
                    ("phone", "Phone Number"),
                ],
                default="email",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="owner",
            name="is_firebase_user",
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(
            name="UserProfile",
        ),
    ]
