# Generated by Django 5.2.7 on 2025-10-13 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_owner_auth_method_owner_is_firebase_user_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='owner',
            name='auth_method',
        ),
        migrations.RemoveField(
            model_name='owner',
            name='is_firebase_user',
        ),
        migrations.AddField(
            model_name='unit',
            name='remaining_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
