# Generated by Django 5.2.7 on 2025-10-13 14:19

import core.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_remove_owner_auth_method_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TenantDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(choices=[('aadhaar', 'Aadhaar Card'), ('rental_agreement', 'Rental Agreement'), ('pan_card', 'PAN Card'), ('police_verification', 'Police Verification'), ('passport', 'Passport'), ('other', 'Other')], max_length=50)),
                ('document_file', models.FileField(upload_to=core.models.tenant_document_upload_path, validators=[core.models.validate_document_file])),
                ('file_name', models.CharField(max_length=255)),
                ('file_size', models.PositiveIntegerField()),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('is_required', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='core.tenant')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tenant_documents', to='core.unit')),
            ],
            options={
                'ordering': ['-uploaded_at'],
                'unique_together': {('tenant', 'document_type')},
            },
        ),
    ]
