# Generated by Django 5.1.13 on 2025-10-21 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_update_pricing_plan_to_units'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pricingplan',
            name='max_units',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='pricingplan',
            name='min_units',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='tenantdocument',
            name='document_type',
            field=models.CharField(choices=[('aadhaar', 'Aadhaar Card'), ('rental_agreement', 'Rental Agreement')], max_length=50),
        ),
    ]
