# Generated by Django 5.1.13 on 2025-10-21 11:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_update_document_types'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tenantkey',
            name='expires_at',
        ),
    ]
