# Generated by Django 5.1.13 on 2025-10-21 12:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_remove_expires_at_from_tenantkey'),
    ]

    operations = [
        migrations.CreateModel(
            name='OwnerPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment_type', models.CharField(choices=[('subscription', 'Subscription Payment'), ('upgrade', 'Plan Upgrade'), ('renewal', 'Plan Renewal'), ('legacy', 'Legacy Payment')], default='subscription', max_length=20)),
                ('payment_method', models.CharField(choices=[('phonepe', 'PhonePe'), ('razorpay', 'Razorpay'), ('manual', 'Manual Entry'), ('bank_transfer', 'Bank Transfer'), ('cash', 'Cash'), ('other', 'Other')], default='phonepe', max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled'), ('refunded', 'Refunded')], default='pending', max_length=20)),
                ('payment_date', models.DateTimeField(blank=True, null=True)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('subscription_start_date', models.DateTimeField(blank=True, null=True)),
                ('subscription_end_date', models.DateTimeField(blank=True, null=True)),
                ('merchant_order_id', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('phonepe_order_id', models.CharField(blank=True, max_length=100)),
                ('phonepe_transaction_id', models.CharField(blank=True, max_length=100)),
                ('payment_gateway_response', models.JSONField(default=dict)),
                ('is_legacy_payment', models.BooleanField(default=False)),
                ('legacy_notes', models.TextField(blank=True, help_text='Notes for legacy payments')),
                ('migrated_from', models.CharField(blank=True, help_text='Source of migration if applicable', max_length=100)),
                ('description', models.TextField(blank=True)),
                ('invoice_number', models.CharField(blank=True, max_length=100)),
                ('receipt_number', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='all_payments', to='core.owner')),
                ('pricing_plan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owner_payments', to='core.pricingplan')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['owner', 'status'], name='core_ownerp_owner_i_bf7553_idx'), models.Index(fields=['payment_date'], name='core_ownerp_payment_f614d7_idx'), models.Index(fields=['merchant_order_id'], name='core_ownerp_merchan_d54a33_idx')],
            },
        ),
    ]
