# Generated by Django 5.1.13 on 2025-10-21 13:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_create_owner_payment_model'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='unit',
            name='maintenance_charge',
        ),
        migrations.RemoveField(
            model_name='unit',
            name='security_deposit',
        ),
    ]
