# Generated by Django 4.2.10 on 2025-10-23 14:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("core", "0019_remove_security_deposit_and_maintenance_fields"),
    ]

    operations = [
        migrations.CreateModel(
            name="ManualPaymentProof",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Amount paid according to the proof",
                        max_digits=10,
                    ),
                ),
                (
                    "payment_proof_image",
                    models.ImageField(
                        help_text="Upload payment receipt/screenshot",
                        upload_to="manual_payment_proofs/",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, help_text="Additional notes about the payment"
                    ),
                ),
                (
                    "verification_status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending Verification"),
                            ("verified", "Verified"),
                            ("rejected", "Rejected"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "verification_notes",
                    models.TextField(
                        blank=True, help_text="Owner's notes about verification"
                    ),
                ),
                ("verified_at", models.DateTimeField(blank=True, null=True)),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="manual_payment_proofs",
                        to="core.tenant",
                    ),
                ),
                (
                    "unit",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="manual_payment_proofs",
                        to="core.unit",
                    ),
                ),
                (
                    "verified_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="verified_payment_proofs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Manual Payment Proof",
                "verbose_name_plural": "Manual Payment Proofs",
                "ordering": ["-uploaded_at"],
            },
        ),
    ]
