# Generated by Django 4.2.10 on 2025-10-28 06:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0020_add_manual_payment_proof"),
    ]

    operations = [
        migrations.CreateModel(
            name="OwnerPayout",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("processing", "Processing"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                            ("retry_scheduled", "Retry Scheduled"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("beneficiary_type", models.CharField(max_length=10)),
                ("cashfree_transfer_id", models.CharField(blank=True, max_length=100)),
                ("cashfree_reference_id", models.CharField(blank=True, max_length=100)),
                ("cashfree_utr", models.CharField(blank=True, max_length=100)),
                ("cashfree_response", models.JSONField(blank=True, default=dict)),
                ("retry_count", models.IntegerField(default=0)),
                ("max_retries", models.IntegerField(default=3)),
                ("last_retry_at", models.DateTimeField(blank=True, null=True)),
                ("next_retry_at", models.DateTimeField(blank=True, null=True)),
                ("initiated_at", models.DateTimeField(auto_now_add=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("error_message", models.TextField(blank=True)),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="received_payouts",
                        to="core.owner",
                    ),
                ),
                (
                    "payment",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="owner_payout",
                        to="core.payment",
                    ),
                ),
            ],
            options={
                "ordering": ["-initiated_at"],
                "indexes": [
                    models.Index(
                        fields=["owner", "status"],
                        name="core_ownerp_owner_i_291984_idx",
                    ),
                    models.Index(
                        fields=["cashfree_transfer_id"],
                        name="core_ownerp_cashfre_716cac_idx",
                    ),
                    models.Index(
                        fields=["status", "next_retry_at"],
                        name="core_ownerp_status_c6cf39_idx",
                    ),
                ],
            },
        ),
    ]
