# Generated by Django 4.2.10 on 2025-11-12 14:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0022_payment_gateway_charge"),
        ("core", "0022_remove_ownersubscriptionpayment"),
    ]

    operations = []
